cart/urls.py
from django.urls import path
from . import views

app_name = "cart"

urlpatterns = [
    path("", views.view_cart, name="view_cart"),
    path("add/<int:product_id>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<int:product_id>/", views.remove_item, name="remove_item"),
    path("increase/<int:product_id>/", views.increase_quantity, name="increase_quantity"),
    path("decrease/<int:product_id>/", views.decrease_quantity, name="decrease_quantity"),
]

mk_mart/urls.py
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from products import views
from django.conf.urls.static import static
from django.shortcuts import render


# home view yahan hi bana sakte ho
def home(request):
    return render(request, "home.html")

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'), 
    path('about/', views.about, name='about'),
    path('products/', include('products.urls')),
    path('cart/', include("cart.urls")),
     path("orders/", include("orders.urls")),
    path("contact/", include("contact.urls", namespace="contact")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = "orders"

urlpatterns = [
    path("checkout/", views.checkout, name="checkout"),
    path("success/<int:order_id>/", views.order_success, name="order_success"),
    path("invoice/<int:order_id>/", views.download_invoice, name="download_invoice"),  
     path('buy/<int:product_id>/', views.buy_now, name="buy_now"),
]   

products/urls.py
# products/urls.py
from django.urls import path
from . import views

app_name = "products" 

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("<int:pk>/", views.product_detail, name="product_detail"),   # yaha pk hai
]
from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    name = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to='products/', null=True, blank=True)
    stock = models.PositiveIntegerField(default=10)

    def __str__(self):
        return self.name


# Create your models here.

products/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Product, Category
from django.shortcuts import render

def home(request):
    return HttpResponse("Welcome to Mk Mart Home Page")

def about(request):
    return render(request, 'products/about.html')

def product_list(request):
    products = Product.objects.all()
    category_id = request.GET.get('category')
    if category_id:
        products = Product.objects.filter(category_id=category_id)
    else:
        products = Product.objects.all()

    categories = Category.objects.all()
    return render(request, 'products/product_list.html', {
        'products': products,
        'categories': categories
    })
def product_detail(request, pk):
    product = get_object_or_404(Product, pk=pk)
    return render(request, "products/product_detail.html", {"product": product})

products/templates/products/about.html
{% extends "base.html" %}

{% block content %}
<section class="py-16 bg-white text-center">
  <h1 class="text-3xl font-bold text-orange-600 mb-6">About Us</h1>
  <p class="text-gray-700 max-w-2xl mx-auto">
    Welcome to Mk Mart! We are committed to providing the best products at the best prices.
    Our goal is to make shopping simple, enjoyable, and affordable.
  </p>
</section>
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<div class="container mt-4 my-5">
    <div class="row">
        <div class="col-md-6">
            {% if product.image %}
                <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.name }}">
            {% else %}
                <img src="{% static 'images/no-image.png' %}" class="img-fluid" alt="No Image">
            {% endif %}
        </div>
        <div class="col-md-6">
            <h2>{{ product.name }}</h2>
            <p><strong>Price:</strong> Rs. {{ product.price }}</p>
            <p>{{ product.description }}</p>

           <!-- <a href="{% url 'cart:add_to_cart' product.id %}" 
   class="btn btn-outline-success btn-sm m-1">
<i class="bi bi-cart-plus"></i>
   Add to Cart</a> -->

         <!-- <a href="{% url 'orders:buy_now'  product.id %}" class="btn btn-outline-warning btn-sm m-1">
      <i class="bi bi-credit-card"></i> Buy Now
    </a> -->

        </div>
    </div>
</div>
{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<h2 class="mb-4">All Products</h2>

<div class="row">
    {% for product in products %}
        <div class="col-md-4 mb-4">
            <div class="card h-100 shadow-sm">
                <!-- Fixed size image -->
                <div style="width: 100%; height: 250px; overflow: hidden;">
                   <!-- <img src="{{ product.image.url }}" 
                         class="card-img-top" 
                         alt="{{ product.name }}" 
                         style="width: 100%; height: 100%; object-fit: contain;"> -->
                         <img src="{{ product.image_url }}" 
     class="card-img-top" 
     alt="{{ product.name }}" 
     style="width: 100%; height: 100%; object-fit: contain;">

                </div>

                <div class="card-body text-center d-flex flex-column">
                    <h5 class="card-title">{{ product.name }}</h5>
                    <p class="card-text">Price: Rs {{ product.price }}</p>

                    <div class="mt-auto">
                        <!-- Buttons with icons -->
                        <a href="{% url 'products:product_detail' product.id %}" class="btn btn-outline-primary btn-sm m-1">
                          <i class="bi bi-eye"></i> View Details
                        </a>
                        <!--<a href="{% url 'cart:add_to_cart' product.id %}" class="btn btn-outline-success btn-sm m-1">
                          <i class="bi bi-cart-plus"></i> Add to Cart
                        </a>
                        <a href="{% url 'orders:buy_now' product.id %}" class="btn btn-outline-warning btn-sm m-1">
                          <i class="bi bi-credit-card"></i> Buy Now
                        </a>-->
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
{% endblock %}